### ISSUE TITLE
Too much logs

### ISSUE THREAD

**Issue by iltercengiz** [visilabs/Visilabs-IOS#1]
You may need the logs while developing the SDK, but users of the SDK don't need them as you do. It messes up with the app's own logs and there's not even a way to disable the logs, other then editing the source code. I suggest you to either provide a way to disable logs totally or don't event log.

Btw, in `VisilabsDefines.h`, there's a logging macro called `DLog` but I didn't see much use of it. Transitioning to this and providing a configuration to log or not may be a good solution.

I thought about implementing this mechanism and later opening a PR, but then decided to open an issue, thinking that log statements may have an important role in your development process.

**Comment by visilabs** [comment]
Thank you for your feedback. In the next release the logs will be optional and by default disabled. The next release will be published in a few weeks.

**Comment by visilabs** [comment]
In 2.5.3 version I disabled logs by default. To see logs of Visilabs SDK you need to use preprocessor macro VISILABSDEBUG=1
